# Generated by Django 2.2 on 2020-02-10 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(blank=True, max_length=50, null=True)),
                ('timeStamp', models.DateTimeField(blank=True, null=True)),
                ('deviceID', models.IntegerField(blank=True, null=True)),
                ('current', models.FloatField(blank=True, null=True)),
                ('voltage', models.FloatField(blank=True, null=True)),
                ('powerFactor', models.FloatField(blank=True, null=True)),
                ('room_temp', models.FloatField(blank=True, null=True)),
                ('Compressor_temp', models.FloatField(blank=True, null=True)),
                ('External_temp', models.FloatField(blank=True, null=True)),
                ('Current_mode_of_AC', models.CharField(blank=True, max_length=10, null=True)),
                ('AC_fan', models.CharField(blank=True, max_length=3, null=True)),
                ('AC_brand', models.CharField(blank=True, max_length=50, null=True)),
                ('Humidity', models.FloatField(blank=True, null=True)),
                ('updated', models.DateTimeField(blank=True, null=True)),
                ('created', models.DateTimeField(blank=True, null=True)),
                ('etag', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
